import {
  IdCard,
  Heart,
  Scale,
  Megaphone,
  HandHeart,
  GraduationCap,
  Briefcase,
  Home,
  Users,
  User,
  Baby,
  HeartHandshake,
  Accessibility,
  Gavel,
  Shield,
  Vote,
  FileSearch,
  Laptop,
  Stethoscope,
  Leaf,
  Car,
  Receipt,
  AlertTriangle,
  Eye,
  Flag,
  Scroll,
  HelpCircle,
  LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "id-card": IdCard,
  "heart": Heart,
  "scale": Scale,
  "megaphone": Megaphone,
  "hands-praying": HandHeart,
  "graduation-cap": GraduationCap,
  "briefcase": Briefcase,
  "home": Home,
  "users": Users,
  "female": User,
  "baby": Baby,
  "heart-handshake": HeartHandshake,
  "accessibility": Accessibility,
  "gavel": Gavel,
  "shield": Shield,
  "vote": Vote,
  "file-search": FileSearch,
  "laptop": Laptop,
  "stethoscope": Stethoscope,
  "leaf": Leaf,
  "car": Car,
  "receipt": Receipt,
  "alert-triangle": AlertTriangle,
  "eye": Eye,
  "flag": Flag,
  "scroll": Scroll,
};

export const getCategoryIcon = (iconName: string): LucideIcon => {
  return iconMap[iconName] || HelpCircle;
};
